### ISSUE TITLE
Finish other python practice exercises on w3resource.com/python-exercises/

### ISSUE THREAD

**Issue by yyfastow** [yyfastow/Practice_python#2]
## TODO

_Exercises left to complete in w3resource python-exercises_
- [x] Python Basic [ 40 Exercises with Solution ]
- [x] Python Data Types - String [ 21 Exercises with Solution ]
- [x]    Python Data Types - List [ 17 Exercises with Solution ]
- [x]    Python Data Types - Dictionary [ 8 Exercises with Solution ]
- [x]    Python Conditional statements and loops [ 16 Exercises with Solution]
- [x]    Python functions [ 16 Exercises with Solution ]
- [ ]    Python Data Structures and Algorithms
  - [x]       Search and Sorting [ 9 Exercises with Solution ]
  - [x]       Recursion [ 11 Exercises with Solution ]
- [ ]   Python Date Time [ 26 Exercises with Solution ]
- [x]   Python Class [ 11 Exercises with Solution ]
- [x]  Python Math [ 15 Exercises with Solution ]
### More Stuff
- [ ] Add in new credit into projects

:tada: :ok_hand: :confetti_ball:

**Comment by yyfastow** [comment]
add more stuff
